### ISSUE TITLE
WebLogic Server

### ISSUE THREAD

**Issue by notebook-t** [notebook-t/notebook-t#7]
# Estructura de Carpetas:
```
- styles
  - style.css
- images
  - web-hosting-software-functions.webp
- index.html
```

Archivo `styles/style.css`:
```css
body {
    font-family: Arial, sans-serif;
    margin: 20px;
    padding: 0;
    background-color: #f5f5f5;
}

.centered {
    text-align: center;
}

h1 {
    color: #333;
}

img {
    width: 100%;
    max-width: 800px;
    height: auto;
    display: block;
    margin: 0 auto;
}

p {
    color: #666;
    line-height: 1.6;
}

form {
    margin-top: 20px;
}

input[type="file"] {
    margin-bottom: 10px;
}

input[type="submit"],
input[type="button"] {
    padding: 10px;
    font-size: 16px;
    cursor: pointer;
    background-color: #007bff;
    color: #fff;
    border: none;
    border-radius: 5px;
}

a {
    color: #007bff;
    text-decoration: none;
}

a:hover {
    text-decoration: underline;
}
```

Archivo `index.html`:
```html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="msvalidate.01" content="63AB90F662EDC928D2F67BBE3BD9BD0F">
    <meta http-equiv="CONTENT-TYPE" content="text/html; charset=UTF-8">
    <link rel="stylesheet" href="styles/style.css"> 
    <title>Visual Studio Code - Web Server</title>
</head>
<body>

<!-- Agrega la etiqueta script con la fuente del proyecto Open Source -->
<script>
    // Agrega tu script aquí
</script>

<header class="centered">
    <h1>Weblogic Server Express</h1> 
</header>

<img src="/images/web-hosting-software-functions.webp" alt="Funciones del software de hosting web">

<p>Un servidor web es un software que forma parte del servidor y tiene como misión principal devolver información (páginas) cuando recibe peticiones por parte de los usuarios. WebLogic Server es un servidor de aplicaciones Java EE (Enterprise Edition) desarrollado por Oracle. Se utiliza para ejecutar aplicaciones empresariales basadas en Java. WebLogic proporciona un entorno robusto para el desarrollo, implementación y gestión de aplicaciones Java empresariales.</p>

<a href="https://prepaenlinea-my.sharepoint.com/:b:/g/personal/231414806_prepaenlinea-sep_edu_mx/EaFXTvM2yIFMlrRaMx2W3pUBs99ECSW-RvXMDpRhgRbKMA?e=NKnHpk" target="_blank">BEA WebLogic Server</a>

<!-- Tu código HTML y contenido aquí -->
<form action="/upload" method="post" enctype="multipart/form-data" class="centered">
    <b>File upload:</b> <br>
    Image<input type="file" name="Img" /> <br>
    Sound<input type="file" name="Snd" /> <br>
    <input type="submit" value="Submit" /> 
</form>

<a href="https://drive.google.com/file/d/1_LcaXG_K7a_WaOWkTWbVDbO7sWdDXR46/view?usp=drivesdk" class="centered" target="_blank">Directory Listing</a>

<input type="button" value="Send Message" onclick="SendMessage('Hello')" class="centered"> 
<font id="txt" size="5" class="centered"></font>

</body>
</html>
```
